### ISSUE TITLE
mini message stuff BUG

### ISSUE THREAD

**Issue by DODIDUM** [Sefiraat/CrystamaeHistoria#118]
This is log in my server.
[latest.log](https://github.com/Sefiraat/CrystamaeHistoria/files/8321521/latest.log)

**Comment by DODIDUM** [comment]
It's loaded in plugin server (turn green) but can't see in the guide book.

**Comment by Sefiraat** [comment]
Nothing to do with Minimessage, which I do not use, you are using Spigot and Crysta is paper only.
