### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RORY112345** [Sefiraat/CrystamaeHistoria#121]
Hey, I've encountered an Error. Weirdly, This error does not appear on Minehut (Minecraft Hosting) but It appears when I host the server with my laptop. The plugin was the same, I uploaded it from my pc.
Error:
[latest.log](https://github.com/Sefiraat/CrystamaeHistoria/files/8341291/latest.log)

**Comment by Sefiraat** [comment]
You’re running Spigot - Crysta requires paper to function correctly.
