### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/CrystamaeHistoria#29]
and it doesnt support sculk sensor just saying
and plz do add all the spawners + spawn eggs if possible + sf stuff!
i know this was a marvelous job but these could make it soooo much better and cooler

**Comment by RIPISDRAD** [comment]
addd sf book too :) but with limited trys !it sounds fun and painful

**Comment by Sefiraat** [comment]
- Skulk sensors are creative only right now so no point adding them yet. 
- I didn't add spawners as the spawner is just one item with it's meta-data being different per mob and I didn't want to have people giving a super rare spawner and getting crap but also dont want a cheap zombie spawner giving good stuff.
- Spawn eggs are creative only

In all of these cases you have the ability to add them manually into your blocks.yml file

idk what you mean by the SF book?
