### ISSUE TITLE
sea pickel

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/CrystamaeHistoria#30]
https://www.toptal.com/developers/hastebin/ujapexapix.yaml
![2021-11-23_07 57 11](https://user-images.githubusercontent.com/76468672/142972504-5c6b8a04-9d60-477a-b52e-9d3ec8848872.png)
yay this again and this happened right now kinda but the emerald one is fixed!

**Comment by RIPISDRAD** [comment]
i dont know why or how but this get fixed and I did literally nothing

**Comment by Sefiraat** [comment]
Closed in favour of Issue #28
