### ISSUE TITLE
trident is drowning

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/CrystamaeHistoria#31]
![2021-11-23_09 54 03](https://user-images.githubusercontent.com/76468672/142979381-1fc8da04-1ddf-410e-91d8-1df52488cc50.png)
it would be nice to see the hole trident

**Comment by Sefiraat** [comment]
Hmmm.... ill look into this

**Comment by Sefiraat** [comment]
This annoys me, but not much I can do about it without either a specific check for this one item (yuck) or changing everything - for now, it stays :(

**Comment by RIPISDRAD** [comment]
Ok man
