### ISSUE TITLE
Duplicate recipes for 3 spells -> not being craftable

### ISSUE THREAD

**Issue by marvjosh1** [Sefiraat/CrystamaeHistoria#49]
The spells "Earth Nova", "Easter Egg" and "Summon Golem" cannot be crafted as they have the exact same crystal combination as another spell.
Leech Bomb - Summon Golem
Phantoms Flight - Easter Egg
Frost Nova - Earth Nova

**Comment by Sefiraat** [comment]
Nice find, fix incoming!
