### ISSUE TITLE
friendly mobs stacking

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/CrystamaeHistoria#5]
hey again 
the issue with spawning friendly mobs and mobstack is that u will notice is that after stacking the first one behave as u predicted
and the others are like vanilla mobs /ch cast FLAME_SPRITE 10 i tried it and the result was said
I ssuggest putting some name tag on them so they wont stack (no error in console btw :))

**Comment by Sefiraat** [comment]
Good idea on the name tags, ill add them in the next release
