### ISSUE TITLE
Spiritual Silken not work

### ISSUE THREAD

**Issue by xMikux** [Sefiraat/CrystamaeHistoria#60]
After using spiritual silken to right click on any blocks, will cause error.
https://pastebin.com/UDCrrbe8

io.github.sefiraat.networks.utils.Theme 

Paper git-Paper-404 (MC: 1.17.1)
Slimefun DEV - 992 (git 0538e345)
CrystamaeHistoria vDEV - 23 (git 1ebf6aaf)

**Comment by Sefiraat** [comment]
Why me r so dumbr
