### ISSUE TITLE
Sentence

### ISSUE THREAD

**Issue by 44wrw44** [Sefiraat/CrystamaeHistoria#63]
Hello, please enable and disable the message about saving data in the config.

**Comment by Sefiraat** [comment]
The message is once every 10 mins and is console only and serves a purpose given that player data is only saved every 10 mins it can be used by server owners/admins to workout rough durations of rollbacks etc. It will not be removed.

**Comment by 44wrw44** [comment]
Just make a config variable to enable and disable the output of this message.

**Comment by Sefiraat** [comment]
Hi there,
I feel like I have answered this fully already above. Please see the above message.

Thanks,
Sefi
