### ISSUE TITLE
Sentence

### ISSUE THREAD

**Issue by 44wrw44** [Sefiraat/CrystamaeHistoria#66]
Hello, add plz support for CoreProtect and WorldGuard flags, otherwise one person thought of using the chaos spell on the spawn.

**Comment by Sefiraat** [comment]
All spells should use the same protection as slimefun. I have just checked that chaos checks who is casting the spell and if they have permission to break blocks. Did you check this before reporting? If you are having issues in which someone who is NOT able to break blocks is able to with Chaos then please record and open another issue. I would leave this one open while awaiting more information but the name 'Sentence' is not suitable and has nothing to do with anything.
