### ISSUE TITLE
/ch cast GYROSCOPIC 1 lagging the sv

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/CrystamaeHistoria#7]
there is a problem with it 
dont know why but after running the command i get laggy like 3 sec delay laggy
/ch cast HELLSCAPE 1 this does too with no errors

**Comment by Sefiraat** [comment]
I'll look into it 👍

**Comment by Sefiraat** [comment]
Can you confirm if this is server lag (TPS goes down) or Client Lag (FPS drops) as I am having no issues with TPS when I use this personally. Ill take a look at FPS for lower end machines separately

**Comment by Sefiraat** [comment]
Hi RIP - We have tested both of these spells extensively and the spark profiling is good for both of them. This seems like client lag which will i'll try to find a way to address

**Comment by RIPISDRAD** [comment]
Ok ill see it and tell it later
