### ISSUE TITLE
Back button not having proper lore.

### ISSUE THREAD

**Issue by MagmaBro123** [Sefiraat/CrystamaeHistoria#78]
Use the plugin.

Also, all Slimefun Guide menus make page turning sounds when switching through them. This addon's menus don't, apparently.

![2022-01-10_10 27 39](https://user-images.githubusercontent.com/51277766/148810828-e6916f2f-4a3b-4f4e-8393-d7f333573403.png)

Normally, with other addons and Base Slimefun:

![2022-01-10_10 29 57](https://user-images.githubusercontent.com/51277766/148810949-30221e18-4a78-48bc-ac8a-5bfb272bde2e.png)

![2022-01-10_10 30 57](https://user-images.githubusercontent.com/51277766/148811108-b64a3c47-3326-49b2-a5b2-056c8da1e237.png)
![2022-01-10_10 30 59](https://user-images.githubusercontent.com/51277766/148811121-f1996736-819c-4009-9b0c-c9647f0de7c5.png)
Airplane is a fork of Paper with better performance features.

**Comment by Sefiraat** [comment]
Yeah, not sure I can do anything about this directly - may have to live with it, annoying I know!

**Comment by MagmaBro123** [comment]
Why do other addons not have this issue then.
