### ISSUE TITLE
Crystamae Liquid Basin GUI won't open.

### ISSUE THREAD

**Issue by MagmaBro123** [Sefiraat/CrystamaeHistoria#81]
Title. Right-clicking on a basin won't open it.

![2022-01-13_22 20 41](https://user-images.githubusercontent.com/51277766/149455886-e566ce58-4cc2-46dd-9480-cb446f749cf1.png)
![2022-01-13_22 20 43](https://user-images.githubusercontent.com/51277766/149455889-ba613588-1ce8-4776-8ac0-5e96dac5e12d.png)

**Comment by Sefiraat** [comment]
That’s… not an issue….

**Comment by MagmaBro123** [comment]
Then how is it used. Rightclicking on it with a crystal or other item does nothing.

**Comment by Sefiraat** [comment]
You drop 'Q' the items in - there are guides within the Slimefun Guide telling you the steps required. Reading those may help you here :)

**Comment by MagmaBro123** [comment]
oH. sORRY.
