### ISSUE TITLE
Some spells bypass towny protections

### ISSUE THREAD

**Issue by Kbryst** [Sefiraat/CrystamaeHistoria#85]
Hello! We were doing some quick testing of each spell on our dev server and found a few that bypass Towny protections (and several that work just fine with it).

Fire nova fully respects town protections, but fireball will bypass them.
Air nova bypasses towny protections. 

Battering ram and Caskada both bypass towny protections, but seem fine to do so.

Shroud fully ignores towny protections.

We also couldn't get Push, Quake, or Time Dilation to work on our dev server, any tips?

**Comment by Sefiraat** [comment]
I’ll check these out and see what I have missed :) 

Push, Quake and Time Dialation should all work fine, you’ll need particles on to see the effect range and nearby mobs to ensure it’s all working. Saying that I’ll do another test on these three to ensure it’s not changed.

**Comment by Sefiraat** [comment]
Hi Kbryst,

I have found an issue in fireball that would apply the fire ticks regardless of protection and will ship that shortly, likewise with Shroud - thanks :)

As for Battering Ram and Cascada, both should be checking for a player who has permission to break the block being moved using Slimefun's default protection manager. Are you able to confirm this issue for me and, if so, provide a video of this.

Similarly I cant see an issue with Air Nova (though it will display the particles regardless of damage/pushback being dealt or not.

Thanks :)
