### ISSUE TITLE
Destroying a block bellow some items drops regular vanilla items.

### ISSUE THREAD

**Issue by GallowsDove** [Sefiraat/CrystamaeHistoria#88]
Reproduction:
1. Place any item that attaches to a block, e.g. Mysterious Flower, Dispersion Lamp or Ender Inhibitor
2. Destroy block that it's attached to
3. Vanilla material drops

While this is an issue that I'm not sure whether is fixable, I think it should at least have a proper bug report.

**Comment by marvjosh1** [comment]
Heya @Sefiraat (sorry for the ping but as this hasnt gotten a response yet),
this is actually an issue that can bother a lot of players.
We were able to reproduce this, heres a clip: https://youtu.be/NQIS9in12U0

**Comment by Sefiraat** [comment]
Heya, this is an issue in Slimefun that I have discussed with people and passed up and I believe there is a PR open and in the works for - this should be resolved with that

**Comment by Sefiraat** [comment]
Going to close this for now, I know the PR is still outstanding but there isn't much I can do until this has been run in - shall revisit it if needs-be.
