### ISSUE TITLE
Recall lattice throwing an error in console

### ISSUE THREAD

**Issue by GentlemanCheesy** [Sefiraat/CrystamaeHistoria#89]
Not sure the context of what caused this error but I found it in console after someone crafted it in-game.

Here is the error:
https://pastebin.com/tCrt7ic7

Currently using:
Slimefun build 999
CrystamaeHistoria build 34

**Comment by GallowsDove** [comment]
For context: This error is thrown when a Recall Lattice is used without being bound to a Waypoint.
